[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Netlify Dev
# https://cli.netlify.com/netlify-dev/#netlifytoml-dev-block

# 제품 모드
[build]
  command = "npm run build"
  functions = "./functions" # Netlify 서버리스 함수가 작성된 디렉토리를 지정합니다.
  publish = "build" # 프로젝트 빌드 결과의 디렉토리를 지정합니다.

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/myFunction"

